### ISSUE TITLE
the matched and bypassed events not always fired

### ISSUE THREAD

**Issue by lionel87** [millermedeiros/crossroads.js#127]
When I trigger a bypassed event with an incorrect URL, at first it works correctly, then later in that session, when I revisit that URL the bypassed event does not fire (nothing happens).
In the same time when I use a correct URL to match a route, then I trigger bypassed with an incorrect URL I can't trigger the previously matched correct route with its URL.

Test case is available on jsfiddle: http://jsfiddle.net/5od9ck56/
Tested with IE11 and Chrome.

**Comment by millermedeiros** [comment]
this happens because the router considers that `bypassed` is not a real "page".. so it did not change from "news en" into something else (you can toggle the behavior with [ignoreState](http://millermedeiros.github.io/crossroads.js/#crossroads-ignoreState))

a better way to implement a 404 page is to:

```js
// ":rest*:" will match any path
// priority set to `-Infinity` so it's the last route to execute
var route404 = crossroads.addRoute(':rest*:', on404, -Infinity);
```

**Comment by lionel87** [comment]
I see your concept now, thanks for your help and quick response!
